version: '3.8'

services:
  bushunter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bus_hunter
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus_hunter_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  postgres_data:

